### ISSUE TITLE
FR: If only one file is needed, don't bother creating the zip file

### ISSUE THREAD

**Issue by thibaultmol** [qgustavor/mkv-extract#35]

**Comment by qgustavor** [comment]
Pull requests are welcome. Relevant code is here: https://github.com/qgustavor/mkv-extract/blob/main/src%2Froutes%2F%2Bpage.svelte#L98

**Comment by qgustavor** [comment]
Things to fix:

- Rename `startZipExtraction` to `startZipCreation`. IDK why I named it wrong 🤷 
- Add a condition [here](https://github.com/qgustavor/mkv-extract/blob/d0c73ebde8e53faea5b208b2ca7e72b75a75baec/src/routes/%2Bpage.svelte#L99) to check if there's just a single stream selected, then handle this case separately in other function.

Code is kinda complex because, in order to reduce memory load, it tries to handle stream extraction by streaming the zip using streamsaver (or using the File Access API, which stores the extracted files direct to the file system without requiring a zip).

**Comment by qgustavor** [comment]
I forgot to fix the function name. 🤦‍♂️
